### ISSUE TITLE
Table of contents should list layers top-first

### ISSUE THREAD

**Issue by ramtechjoe** [Esri/arcgis-toolkit-dotnet#134]
The list is upside down.  The base layer is at the top and the layers are in reverse order that they were added

**Comment by dotMorten** [comment]
The TOC presents layers in the order it's given. If you want to present layers in an opposite order, bind a list that has the layers in the opposite order.

Please log a separate issue with the exception, including exception and repro details, for separate tracking

**Comment by ramtechjoe** [comment]
I would think the default behavior of the tool would be to stack the layers in the order they are added.  This is how any other similar type of control works and the behavior of desktop applications.  The default process is to create a basemap and then add layers to the map.  In this case the basemap should be on the bottom, it seems this should not require changes to the default binding.

**Comment by dotMorten** [comment]
> I would think the default behavior of the tool would be to stack the layers in the order they are added

That's exactly what it is doing. The first layer you add, is the first layer listed.

> In this case the basemap should be on the bottom

If it's added first, it would be on top.

**Comment by ramtechjoe** [comment]
When you add data in ArcMap, ArcPro, or any other map application you would add a basemap and then add layers.  The TOC reflects the order that the layers are added from bottom (0) to top (Y).  It seems you are suggesting I should add layers in the opposite order (or by default basemaps are always put on the bottom)

The approach to create a map in Runtime API is to create a map as a basemap type Map map = new Map(Basemap.CreateStreets());

And then to add layers to that map.  A ToC should present those layers with the first layer at the bottom not at the top.  In the case below I added PipesByOwner 1st and VPI (top most layer) last


This shown below is an incorrect presentation of the map layers based on the common understanding of how layers should be presented in a Table of Contents.  I understand that it works as designed, but this is an incorrect design

[cid:image001.png@01D30BA8.73F28040]

**Comment by dotMorten** [comment]
Added a new property to reverse the layer ordering (and it's on by default). It was actually partially doing it, but due to a bug it would only work if you refreshed the ToC by turning the legend on. There's a new checkbox in the test app that allows you to flip the property on and off.
Note: Sublayers aren't reversed currently.

**Comment by ramtechjoe** [comment]
Thank you for the fix.  Will the nuget package be upgraded with the new release?  I appreciate your attention to the issue

Thanks Again
-joe


Joe Hershman
Senior Consultant / Program Manager
 [RAMTECH Email Logo]
RAMTeCH Software Solutions Inc.
6303 Osgood Avenue North, Stillwater, MN 55082
Tel: (970)481-0989, (970)416-1404  Fax: (651) 430 0201

**Comment by dotMorten** [comment]
@ramtechjoe We don't have any specific dates for a nuget update. We'll probably drop another one when we have added more of the controls we're planning on adding, and/or updated the existing ones to closer match the toolkit designs we're currently working on establishing across all the runtimes. Xamarin is also about to come live, so that might be another reason to soon release a beta3. Until then, you should be able to just clone this repo and hit "build" and you'll get a nuget-package as output.

**Comment by dotMorten** [comment]
NuGet update coming... you can use the AppVeyor nuget server until then (see the readme on the front page of the repo)
