### ISSUE TITLE
Scalebar on Android uses wrong converted MapScale

### ISSUE THREAD

**Issue by P-e-t-e-r** [Esri/arcgis-toolkit-dotnet#319]
The scalebar implementation for android delivers not the same results for scale calculations as UPW or iOS. The used mapScale seems to be off for a constant factor.

**Comment by dotMorten** [comment]
@P-e-t-e-r could you share some examples/screenshots?

**Comment by P-e-t-e-r** [comment]
Hey @dotMorten ,
I just did something like this:
<esriUI:MapView Grid.RowSpan="3" x:Name="MapView" Map="{Binding Map, Source={StaticResource MapViewModel}}" />
<forms:ScaleLine Grid.Row="1" HorizontalOptions="Start" VerticalOptions="End" Margin="20"
                             MapView="{x:Reference MapView}"/>

practically taken from your own samples.

Tested on an windows 10 machine and an android tablet (samsung Galaxy Tab S5e)
![issue_319_scalebar_android](https://user-images.githubusercontent.com/16098203/76439597-d9884300-6379-11ea-8565-549e4a1e963b.jpg)
![issue_319_scalebar_uwp](https://user-images.githubusercontent.com/16098203/76439613-df7e2400-6379-11ea-8c1b-5c04382dc56d.PNG)


Cheers,
Peter

**Comment by P-e-t-e-r** [comment]
the upper sreenshot is android
the lower windows UWP

**Comment by dotMorten** [comment]
Thank you. Very helpful. I do think I just found an issue with the API for Forms: The UnitsPerPixel that is used here is reported wrong for Android when using Forms (it's reporting it using raw pixels and not the DIPs that Forms uses), and that's actually not a toolkit bug, but in the main Runtime Forms SDK.

One way you could work around that for now is to set the `MapScale` instead of the `MapView` property: `MapScale="{Binding MapScale, Source={x:Reference MapView}}" `

Just note that this won't try and calculate the scale for the center of the view, so for some projections the distortion starts becoming a factor.

As a quick workaround, you could change this line here:
https://github.com/Esri/arcgis-toolkit-dotnet/blob/master/src/Toolkit.Forms/ScaleLine/ScaleLine.cs#L125
And alter the `view.UnitsPerPixel` by the screen scale of your device when running on Android.

There's a similar bug in the native android scaleline control, because that one "forgot" to take into account that android doesn't report this value in DIPs, so that's easily addressable by applying this fix. However I'm a little reluctant to make the same fix to Forms, because the bug isn't actually in the toolkit (I'm fixing this bug in the Runtime as we speak, so 100.8 would have the fix).

**Comment by dotMorten** [comment]
Verified fixed with the upcoming v100.8 release:

![image](https://user-images.githubusercontent.com/1378165/79628805-2db0e080-80f9-11ea-8584-30c4c97a21da.png)

**Comment by P-e-t-e-r** [comment]
Very nice! Looking forward to use it!
